services:
  db:
    image: postgres:18.0-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql
    environment:
      - PGDATA=/var/lib/postgresql
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.cache/redis-data:/data

  nats:
    image: nats:2.12-alpine
    restart: unless-stopped
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222

  grafana:
    image: grafana/grafana:main-ubuntu
    restart: unless-stopped
    volumes:
      - ./.cache/grafana-data:/var/lib/grafana
      - ./.cache/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    volumes:
      - ./.docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.cache/prom-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/jaeger:2.12.0
    restart: always
    ports:
      - 16686:16686 # UI
      - 4317:4317
      - 4318:4318
