global:
  scrape_interval: 5s
  external_labels:
    monitor: "hw-go"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["app:9091"]
